### ISSUE TITLE
Fresh install on new server error

### ISSUE THREAD

**Issue by chri55mith** [mkdo/cpd-theme#2]
When I activate the plugin I get the following error:

Fatal error: Call to undefined function get_blog_details() in /home/cluster-sites/1/c/cpd-portfolio.net/public_html/wp-content/plugins/cpd/cpd.php on line 227

**Comment by mwtsn** [comment]
Hi Chris,

That error occurs when the WordPress install is not configured as multisite. Can you confirm that you have a multisite install?

**Comment by chri55mith** [comment]
Apologies Matt, my htaccess file didn't update with the new commands.

**Comment by mwtsn** [comment]
No worries Chris, happy to help.
