### ISSUE TITLE
New system initial setup prblem

### ISSUE THREAD

**Issue by chri55mith** [mkdo/cpd-theme#3]
Brand new system

3 users

1 super admin 

1 Supervisor 

1 Participant 

When logged in as the participant it doesn’t forward me to my participants journal dashboard URL so it claims (and rightly so) I don’t have permission to edit because I’m still at root.

I then have to manually type my journal URL (it does not tell me what this is) before I can edit journals etc.

**Comment by mwtsn** [comment]
Hi Chris, 

Closing this down because it does not relate to the them. The correct issue log is here: https://github.com/mkdo/cpd/issues

This should auto-forward, does the participant have a journal other than root assigned to them?

**Comment by chri55mith** [comment]
Yes the participant has his own journal assigned. He does not have the root assigned.

**Comment by chri55mith** [comment]
I can't see anything in the issue log link you gave that relates to participant not getting forwarded to their journal dashboard?

**Comment by mwtsn** [comment]
Hi Chris, 

This is the issues log for the CPD theme. 

You need to be using the issues log for the CPD Plugin:

https://github.com/mkdo/cpd/issues

Not 

https://github.com/mkdo/cpd-theme/issues

**Comment by mwtsn** [comment]
Also all Participants are given access to the root theme as a subscriber, so that part is not an error.

**Comment by chri55mith** [comment]
Sorry Matt - just not used to github!

**Comment by mwtsn** [comment]
No worries Chris, easy mistake

**Comment by mwtsn** [comment]
Hi Chris,

If I am fully logged out of the system, and I log in as bo1cps with the details you have provided it redirects me to http://www.cpd-portfolio.net/bo1cps/wp-admin/

This is working as expected.

**Comment by chri55mith** [comment]
It is working now! Did you change anything? I was really methodical in my approach this time but now it works.

**Comment by mwtsn** [comment]
On my life I didn't change a thing Chris.

**Comment by chri55mith** [comment]
:) OK. 

I have given the 3 users easy names so there's no confusion for next week.
