### ISSUE TITLE
Categories widget styling glitch

### ISSUE THREAD

**Issue by chri55mith** [mkdo/cpd-theme#4]
![theme-styling-glitch](https://cloud.githubusercontent.com/assets/11389908/11274353/415e2c16-8ed0-11e5-941c-7ce91a6e54b9.png)

See attached image, the categories box styling has no padding and looks different to the rest.

**Comment by mwtsn** [comment]
Hey @davetgreen this might be a quick fix, when you get chance.

**Comment by davetgreen** [comment]
@chri55mith @mwtsn I've added a small tweak to the theme styles to put some padding on that paragraph holding the "No Categories" text. This will also resolve the problem in any other widgets.

Just replace the style.css and style.css.map files in the theme on the server with the latest ones from this repo.
